### ISSUE TITLE
resume() and pause() functionality are reversed.

### ISSUE THREAD

**Issue by ConnorTroy** [RookAndPawn/pausable_clock#3]
Creating a PausableClock instance with paused set to true returns a clock which is not paused. The resume() method pauses the clock and the pause() method resumes the clock.

**Comment by johnhurt** [comment]
Whoops! I don’t know how I missed that. I’ll try to get a new release out later today. Thanks for reporting it!

**Comment by johnhurt** [comment]
I added a test in a pr here to verify that behavior, but my test works as expected.

https://github.com/RookAndPawn/pausable_clock/pull/4/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R1090-R1116

Can you post an example where you see the reversed behavior?

**Comment by ConnorTroy** [comment]
I see. now() does seem to work correctly. I was pulling the time using now_std() assuming they are interchangeable. Is this not the case?

**Comment by johnhurt** [comment]
Hmm, they should be. now_std() takes the output of now() and turns it into a std Instant. If that's not being done correctly, then something is really wrong. I'll update my test to do the same thing and see what that uncovers. Thanks again for filing this bug.

**Comment by ConnorTroy** [comment]
Thanks for checking it out. I'm using `clock.now_std().elapsed().as_secs()` to check time. I could be doing something wrong though. Let me know if you need any more info.

**Comment by johnhurt** [comment]
Oooooh. I think I understand what's going on. When you call `elapsed()` on the `std::time::Instant` returned from `clock.std_now()`, it doesn't know that the Instant is kind of artificial because it's from a pausable clock (and not the real clock), so it is telling you how much time has elapsed since that artificial instant. That gives you the reversed behavior you were seeing because:

- When the clock is paused, that instant doesn't change, so the elapsed duration between now and the paused instant increases.
- When the clock is running, the instant moves at the same rate as std now, so the elapsed time doesn't change.

What that tells me is `clock.now_std()` should be removed in favor of enhancing the methods on `PausableInstant` to bring it to parity with `std::time::Instant`. That would prevent this sort of (totally reasonable) mistake.

Since that might take a while, I would recommend using `clock.now().elapsed_millis()`. That should have the behavior you were expecting.

I really appreciate your engagement with this project. I'll leave this issue open until I make the changes I mentioned above.

**Comment by ConnorTroy** [comment]
Gotcha gotcha, I figured that might be what's happening but I wasn't exactly sure what the expected behavior was supposed to be. Thanks a bunch for the help!

**Comment by johnhurt** [comment]
My pleasure. Thanks for your feedback. I'll leave a note here when I update the PausableInstant functionality.

**Comment by johnhurt** [comment]
I just published version 1.0.0 of this library with some enhancements to the PausableInstant type to bring it to parity with std::time::Instant. 

Take a look at `PausableInstant::elapsed.` It should do what you want. Unfortunately, you have to pass it a reference to the clock that created it, so it's not as seamless as `std::time::Instant::elapsed`, but at least it's correct :P
